### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by Julissamigdalia** [SistemasTecTlaxiaco/actividad-1-infografia-Julissamigdalia-1#1]
[INFOGRAFIA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-Julissamigdalia-1/files/14275954/INFOGRAFIA.pdf)

**Comment by JeroRoque** [comment]
calificación: 18/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
